// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkyEZj7Jyuqllbev6db1z2RazdQBJsmY',
    appId: '1:712594885771:web:a97e089d9f038fe554588e',
    messagingSenderId: '712594885771',
    projectId: 'scamradar-a2e11',
    authDomain: 'scamradar-a2e11.firebaseapp.com',
    storageBucket: 'scamradar-a2e11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDckAgJIP_epAOCrWXlijjRFiFhIIhXYNY',
    appId: '1:712594885771:android:1fa34b6665e8f42454588e',
    messagingSenderId: '712594885771',
    projectId: 'scamradar-a2e11',
    storageBucket: 'scamradar-a2e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVApQ8yhnMOji_pizQJO70Aazn2qziHg',
    appId: '1:712594885771:ios:ce07ccdcb2d8bbc554588e',
    messagingSenderId: '712594885771',
    projectId: 'scamradar-a2e11',
    storageBucket: 'scamradar-a2e11.firebasestorage.app',
    iosBundleId: 'com.example.scamradar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVApQ8yhnMOji_pizQJO70Aazn2qziHg',
    appId: '1:712594885771:ios:ce07ccdcb2d8bbc554588e',
    messagingSenderId: '712594885771',
    projectId: 'scamradar-a2e11',
    storageBucket: 'scamradar-a2e11.firebasestorage.app',
    iosBundleId: 'com.example.scamradar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKkyEZj7Jyuqllbev6db1z2RazdQBJsmY',
    appId: '1:712594885771:web:fa1deabd68fee7bb54588e',
    messagingSenderId: '712594885771',
    projectId: 'scamradar-a2e11',
    authDomain: 'scamradar-a2e11.firebaseapp.com',
    storageBucket: 'scamradar-a2e11.firebasestorage.app',
  );
}
